### ISSUE TITLE
ShadowDriveClient Work With Only Mainnet

### ISSUE THREAD

**Issue by anujkumarthakur** [GenesysGo/shadow-drive-rust#49]
1. Shadow Drive Client Woking With Only MainNet (**'https://api.mainnet-beta.solana.com'**)
     ```
    //create shdw drive client
    let shdw_drive_client = ShadowDriveClient::new(keypair, "https://api.mainnet-beta.solana.com");
     
    ```
2. I would like to be Work With Localnet , How I can do it ?

**Comment by tracy-codes** [comment]
This is intentional, as the program and shadow token and storage service is only available on mainnet. You can use any mainnet rpc provider that allows the full set of solana rpc calls.
